# Generated by Django 5.2 on 2025-07-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
