# Generated by Django 5.2 on 2025-07-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_session_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
